### ISSUE TITLE
Loading libclang failed

### ISSUE THREAD

**Issue by tonnico** [ttsiodras/dotvim#3]
Hi,

I found your pretty nice compilation with google. But I'm stuck with the libclang feature. Probably you have an idea what's going wrong?

I'm pretty new with VIM and the config. Is there something missing in the .vimrc? I followed your instruction. 

```
Loading libclang failed, completion won't be available. Consider setting g:clang
_library_path.
```
___
Nico

**Comment by Wurstnase** [comment]
*Insert random facepalm...*
I should install clang itself...
